language: rust
rust:
  - stable
  - nightly
script:
  - cargo build
  - |
    [ $TRAVIS_RUST_VERSION != nightly ] ||
    cargo build --features nightly
  - |
    [ $TRAVIS_RUST_VERSION != nightly ] ||
    cargo test --features "unstable"
  - |
    [ $TRAVIS_RUST_VERSION != nightly ] ||
    cargo test --features "nightly unstable"
  - cd demo/quicksort && cargo build && cd ../../
  - cd demo/sieve && cargo run --release && cd ../../
  - |
    [ $TRAVIS_RUST_VERSION != nightly ] ||
    ( cd demo/nbody && cargo run --release -- bench && cd ../../ )
